### PR TITLE
WIP: Render error messages with full page layout if possible

### PR DESCRIPTION
**Pull request by Nutomic**
Currently error messages are rendered as plain text on a completely empty page. It should be possible to include the normal page design with header, footer etc.

Not working yet.

### CODE REVIEW

**Comment by Tealk** [comment]
if you just fade it in via js as a modal?
https://getbootstrap.com/docs/5.2/components/modal/

**Comment by Nutomic** [comment]
That would require too many changes, and besides i would have to use js 😭

**Comment by Tealk** [comment]
The question is, do we want to continue using something outdated or develop it further?
We can stay with the design but add new features?

**Comment by Nutomic** [comment]
There is nothing outdated, it just needs some changes to render error messages more nicely. Using a modal for errors would require a complete rewrite of the project, so that requests are made from javascript, instead of using simple links. Then javascript would be mandatory which i want to avoid.

**Pull request merged**
