### PR TITLE
Fix length username

### PR DESCRIPTION
**Pull request by Tealk**
shortens the length of the username so that it does not overlap the border

### CODE REVIEW

**Comment by Nutomic** [comment]
Can you include a screenshot for design changes like this? Would make it much easier to review.

**Comment by Nutomic** [comment]
Wouldnt it be better to wrap to a new line so that it can still be read?

**Comment by Tealk** [comment]
like this?
image

**Comment by Nutomic** [comment]
Yes i like that better. Thanks!

**Pull request merged**
