### PR TITLE
Add header logo from site.banner (ref #24)

### PR DESCRIPTION
**Pull request by Nutomic**
For now you need to set the logo in lemmyui admin settings (called banner). It needs to be 149px wide and 52px high, otherwise it will be cut off.

### CODE REVIEW

**Comment by Tealk** [comment]
I would have even started something once
https://github.com/LemmyNet/lemmyBB/tree/custom-logo

**Comment by Nutomic** [comment]
There is no need to use an env var for this as we can just store data via Lemmy which is much cleaner.

**Comment by Tealk** [comment]
I didn't know that at the time, but I even removed it in the last commit.

but it is still missing css so that the design is not destroyed.

**Comment by Tealk** [comment]
If i try the changes i get
```
[2022-11-02T12:09:50Z INFO  rocket::server] GET / text/html:
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://localhost:8536/api/v3/site): error trying to connect: tcp connect error: Connection refused (os error 111)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)', src/site_fairing.rs:52:67
[2022-11-02T12:09:50Z ERROR _] Handler index panicked.
[2022-11-02T12:09:50Z WARN  _] A panic is treated as an internal server error.
[2022-11-02T12:09:50Z WARN  _] No 500 catcher registered. Using Rocket default.
```

**Comment by Tealk** [comment]
> It needs to be 149px wide and 52px high, otherwise it will be cut off.

Not anymore, the size is now adjusted

**Comment by Nutomic** [comment]
Thanks! But you accidentally pushed a change to the translations submodule, i had to revert that.

**Pull request merged**
